export const ADD_PRODUCT_TO_BASKET = "ADD_PRODUCT_TO_BASKET";

export const DELETE_PRODUCT_FROM_BASKET = "DELETE_PRODUCT_FROM_BASKET";

export const CHANGE_NUMBER_OF_ORDER = "CHANGE_NUMBER_OF_ORDER";

export const FAIL_PAYMENT = "FAIL_PAYMENT";
